[package]
name = "breeze"
version = "0.1.0"
description = "A wrapper around Bevy for easier game development."
keywords = ["bevy", "game-development", "graphics", "wrapper"]
categories = ["game-development"]
license = "MIT"
edition = "2024"

[dependencies]
bevy = { version = "0.17.3" }
bevy_vector_shapes = "0.11.0"